INSERT INTO role (name) VALUES ('USER') ON CONFLICT (name) DO NOTHING;
INSERT INTO role (name) VALUES ('LIBRARIAN') ON CONFLICT(name) DO NOTHING;
INSERT into role (name) VALUES ('SUPERADMIN') ON CONFLICT(name) DO NOTHING;